---
name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version:
          - 6.0.x
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
      - uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore AniDownloaderTerminal.sln
      - name: Build
        run: dotnet build AniDownloaderTerminal.sln
      - name: Publish
        run: dotnet publish AniDownloaderTerminal.csproj -c Release -r linux-x64 --self-contained /p:PublishSingleFile=true /p:PublishSelfContained=true
